server:
  port: 9000

spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:mysql://localhost:3306/matching?serverTimezone=Asia/Seoul
    username: sally
    password: 1q2w3e4r
    driver-class-name: com.mysql.cj.jdbc.Driver